Feature exe01 - Solicitação de PR
NataliTrindade/repo-exercicios-orion-bootcamp pull request #1
Opened 2023-10-10 14:00 UTC by NataliTrindade

2023-10-11 02:18 UTC, dairsposito requested changes
Gostei da sua percepção na tratativa de erros inesperados, validando a palavra fornecida. No entanto, é bom estar atenta para não adicionar regras que não estão no escopo do exercício.

2023-10-11 02:18 UTC, dairsposito commented on exercicios/exe01/assets/js/index.ts
> +  if (word.length === 0) {
Neste caso recomendo considerar sobre early returns ou até mesmo um switch case.

2023-10-11 02:18 UTC, dairsposito commented on exercicios/exe01/assets/js/index.ts
> +  const errors: string[] = [
Qual seria a necessidade de criar um array com os erros? Uma vez que para cada posição do array há apenas uma condição que a retorna.

2023-10-11 02:18 UTC, dairsposito commented on exercicios/exe01/assets/js/index.ts
> +  return `A palavra "${word}" possui ${word.length} letras e ${totalVowels} ${showVoelOrVowels}.`;
Retornar apenas a quantidade de vogais.

2023-10-11 02:18 UTC, dairsposito commented on exercicios/exe01/assets/js/index.ts
> +const executeValidation = (word: string): string | any => {
Não colocar any em retorno de funções, procurar sempre definir os tipos de retorno. Ainda mais junto com outros tipos, uma vez que any abrange todos os tipos de retorno.

2023-10-11 02:18 UTC, dairsposito commented on exercicios/exe01/assets/js/index.ts
> +  if (typeof validationResult !== "string") {
Considerar utilizar um ternário para retorno da função.

2023-10-11 02:18 UTC, dairsposito commented on exercicios/exe01/assets/js/index.ts
Documentar as funções.

2023-10-11 02:18 UTC, dairsposito commented on exercicios/exe01/assets/js/index.ts
> +const btn = document.querySelector(".btn") as HTMLElement;
Sugiro não fazer a query utilizando a classe do botão, uma vez que se vier a existir outros botões, os mesmos irão disparar o evento.

2023-10-11 11:02 UTC, NataliTrindade commented
> Gostei da sua percepção na tratativa de erros inesperados, validando a palavra fornecida. No entanto, é bom estar atenta para não adicionar regras que não estão no escopo do exercício.

Obrigada pela observação, decidi por remover o que não foi solicitado no exercício para manter a objetivo dele e realizei a documentação das funções.

2023-10-12 01:48 UTC, dairsposito requested changes

2023-10-12 01:48 UTC, dairsposito commented on exercicios/exe01/assets/js/index.ts
> +  return `Quantidade de vogais: ${totalVowels}`;
A função deve retornar somente a quantidade de vogais na palavra.
Sugiro que você coloque os console.log() fora do escopo da função também.
Lembrando que além de exibir o valor em tela, deverá ser printado no console o valor fornecido por parâmetros.

2023-10-12 02:23 UTC, merged